// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdJ0IiYcEWmkL28HC-qRUjsL7zLWnwAWw',
    appId: '1:918372304242:web:4d770bbdd882b459cb09eb',
    messagingSenderId: '918372304242',
    projectId: 'pharmacyclients-db839',
    authDomain: 'pharmacyclients-db839.firebaseapp.com',
    storageBucket: 'pharmacyclients-db839.appspot.com',
    measurementId: 'G-TZF6LLF6PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqDtZEmorWyt9EkhIqj_ee8B4sik84N7E',
    appId: '1:918372304242:android:896056d460fd126ccb09eb',
    messagingSenderId: '918372304242',
    projectId: 'pharmacyclients-db839',
    storageBucket: 'pharmacyclients-db839.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPT_L__OP-cIRpfScSDR1IJHNr5MeR2ZQ',
    appId: '1:918372304242:ios:892118797d14f1adcb09eb',
    messagingSenderId: '918372304242',
    projectId: 'pharmacyclients-db839',
    storageBucket: 'pharmacyclients-db839.appspot.com',
    iosBundleId: 'com.example.pharmacyClients',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdJ0IiYcEWmkL28HC-qRUjsL7zLWnwAWw',
    appId: '1:918372304242:web:e2797190502ae0bacb09eb',
    messagingSenderId: '918372304242',
    projectId: 'pharmacyclients-db839',
    authDomain: 'pharmacyclients-db839.firebaseapp.com',
    storageBucket: 'pharmacyclients-db839.appspot.com',
    measurementId: 'G-NCQDJ0TY8J',
  );
}
