// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYXxHriPy-2sYDDYIYr6jF30eLtmxuJxE',
    appId: '1:810747540971:web:dff05f29c166e9ac61d5ae',
    messagingSenderId: '810747540971',
    projectId: 'pharmacyclients-db9a4',
    authDomain: 'pharmacyclients-db9a4.firebaseapp.com',
    storageBucket: 'pharmacyclients-db9a4.appspot.com',
    measurementId: 'G-8D7Y7BW3Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwrYAH8Me7Xun0XnxYy8n-9693Z5MoTpo',
    appId: '1:810747540971:android:f22656899714b0ee61d5ae',
    messagingSenderId: '810747540971',
    projectId: 'pharmacyclients-db9a4',
    storageBucket: 'pharmacyclients-db9a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdn0f6cNV8lEfa3SQ2FM5sbQqDCGKW02w',
    appId: '1:810747540971:ios:24332584e7048d9361d5ae',
    messagingSenderId: '810747540971',
    projectId: 'pharmacyclients-db9a4',
    storageBucket: 'pharmacyclients-db9a4.appspot.com',
    iosBundleId: 'com.example.pharmacyClients',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYXxHriPy-2sYDDYIYr6jF30eLtmxuJxE',
    appId: '1:810747540971:web:72d5bd9c0ac96ce461d5ae',
    messagingSenderId: '810747540971',
    projectId: 'pharmacyclients-db9a4',
    authDomain: 'pharmacyclients-db9a4.firebaseapp.com',
    storageBucket: 'pharmacyclients-db9a4.appspot.com',
    measurementId: 'G-R4WWELS566',
  );
}
